name: master
on:
  push:
    branches:
      - master
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    with: 
      fetch-depth: '0'
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master    
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@karhoo'
    - run: npm run bootstrap
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
    - run: npm run lint
    - run: npm run build
    - run: npm run test
    - run: npx lerna publish from-package --yes
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
