name: On pull request
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
        scope: '@karhoo'
    - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    - run: npm run bootstrap
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    - run: npm run lint
    - run: npm run build
    - run: npm run test
